version: "3.8"

services:
  db:
    image: postgres:latest
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    env_file:
      - .env
    networks:
      - db_network
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DATABASE}
  flaskapp:
    build: .
    restart: always
    env_file:
      - .env
    volumes:
      - .:/opt/services/flaskapp/src
    depends_on:
      - db
    links:
      - db:db
    networks:
      - web_network
      - db_network
    expose:
      - 5090
  nginx:
    image: nginx:latest
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    networks:
      - web_network
    ports:
      - "8080:80"
    depends_on:
      - flaskapp

networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge
volumes:
  dbdata:
